import type { NextPage } from "next";
import Head from "next/head";

import { siteData } from "../data/data";
import TopContactBanner from "../components/TopContactBanner";
import TopNavigationBar from "../components/TopNavigationBar";
import HeroSection from "../components/HeroSection";
import AboutSection from "../components/AboutSection";
import TeamSection from "../components/TeamSection";
import ContributorsSection from "../components/ContributorsSection";
import ImageGallerySection from "../components/ImageGallerySection";
// import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopContactBanner contact={siteData.contact} />

        <TopNavigationBar />

        <HeroSection contact={siteData.contact} />

        <AboutSection />

        <ImageGallerySection gallery={siteData.images} />

        <TeamSection team={siteData.founders} />

        <ContributorsSection contributors={siteData.contributors} />
      </main>

      <footer></footer>
    </>
  );
};

export default Home;
