import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { siteData } from "../data/data";
import TopContactBanner from "../components/TopContactBanner";
import TopNavigationBar from "../components/TopNavigationBar";
// import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopContactBanner contact={siteData.contact} />

        <TopNavigationBar />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
